# ==========================================
# PERIPHERAL-SPECIFIC OLED WIDGETS (Nur Rechts)
# ==========================================

# Animation auf der rechten Seite anzeigen
CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL=y
CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_CAT=n
CONFIG_NICE_OLED_WIDGET_ANIMATION_PERIPHERAL_GEM=y

# Aktiviert die Split-Verbindung auf der rechten Seite
CONFIG_ZMK_SPLIT=y
