# ==========================================
# CENTRAL-SPECIFIC OLED WIDGETS (Nur Links)
# ==========================================

# Active Layer anzeigen
CONFIG_NICE_OLED_WIDGET_LAYER=y
CONFIG_NICE_OLED_WIDGET_LAYER_CUSTOM_X=-38
CONFIG_NICE_OLED_WIDGET_LAYER_CUSTOM_Y=90

# WPM-Berechnung und Tacho-Widgets aktivieren
CONFIG_ZMK_WPM=y
CONFIG_NICE_OLED_WIDGET_WPM=y
CONFIG_NICE_OLED_WIDGET_WPM_NUMBER=y
CONFIG_NICE_OLED_WIDGET_WPM_LUNA=n
CONFIG_NICE_OLED_WIDGET_WPM_BONGO_CAT=n
CONFIG_NICE_OLED_WIDGET_WPM_SPEEDOMETER=n
CONFIG_NICE_OLED_WIDGET_WPM_GRAPH=y

# Modifikatoren-Anzeige unten anzeigen
CONFIG_NICE_OLED_WIDGET_MODIFIERS_INDICATORS=y
CONFIG_NICE_OLED_WIDGET_MODIFIERS_INDICATORS_FIXED=y
CONFIG_NICE_OLED_WIDGET_MODIFIERS_CUSTOM_X=0
CONFIG_NICE_OLED_WIDGET_MODIFIERS_CUSTOM_Y=104
CONFIG_NICE_OLED_WIDGET_MODIFIERS_INDICATORS_FIXED_SYMBOL_MACOS=n
CONFIG_NICE_OLED_WIDGET_MODIFIERS_INDICATORS_FIXED_SYMBOL_WINDOWS=y
