manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: cormoran
      url-base: https://github.com/cormoran
    - name: mctechnology17
      url-base: https://github.com/mctechnology17

  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml

    - name: zmk-module-ble-management
      remote: cormoran
      revision: main
      import: true

    - name: zmk-module-settings-rpc
      remote: cormoran
      revision: main
      import: true

    - name: zmk-module-battery-history
      remote: cormoran
      revision: main
      import: true

    - name: zmk-nice-oled
      remote: mctechnology17
      revision: main

  self:
    path: config
